name: document

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Display python version
        run: python3 -c "import sys; print(sys.version)"

      - name: Install Sphinx dependencies
        run: sudo apt-get install python-dev build-essential

      # Note it is better using requirements.txt to install required packages
      - name: Install Sphinx + requirements via pip
        run: pip install -r requirements.txt

      - name: Build documentation
        run: make html

      # Posting to GitHub Pages
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.MY_ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build/html
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}